<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表情包</title>
    <link href="../css/stylus.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class="icon">
	  <div class="frog" id="frog-3">

		<div class="body">
		  <div class="mouth">
			<div class="toungue"></div>
		  </div>
		</div>

		<div class="eyes">
		  <div class="eye eye-left wink">
			<div class="eye-inner">
			  <div class="pupil">
				<div class="light"></div>
			  </div>
			</div>
		  </div>
		  <div class="eye eye-right">
			<div class="eye-inner">
			  <div class="pupil">
				<div class="light"></div>
			  </div>
			</div>
		  </div>
		</div>

	  </div>
	</div>
</body>
</html>